### PR TITLE
Add support for specific servers

### PR DESCRIPTION
**Pull request by marvin1099**
Add support for specific servers as requested by:
https://github.com/phirecc/wgnord/issues/5

I'm doing this by taking the letters / number from "wgnord c"
and if numbers are at the end of "wgnord c" like for "wgnord c  de333"
in get_contry_code we remove the number 
and in the sever selection we use only the number.
Then we check if that number exists in the hostnames.
If not we try once more whit a higher limit.
from there if can stop
- if there are less results than limits (no more servers to use)
- the index was found
- or if there was no number in the first place it will stop on the first try
Then if there is no index we select 0 (best server).
The rest basically works the same.

Be happy for any and all ideas, to make this  better

### CODE REVIEW

**Comment by phirecc** [comment]
Cool that you're working on this.
I think there may be a more elegant solution using the API itself. There is probably an endpoint for getting the info for a specific server identifier (like de333).
Back when I wrote this script I had to reverse engineer the client to figure out the API. Apparently the client is open source now: https://github.com/NordSecurity/nordvpn-linux

See https://github.com/NordSecurity/nordvpn-linux/blob/a56dc8557b1d361b4352a18efd7daaf4014d6612/core/urls.go#L97

The script currently makes a request to this API endpoint (URIdecoded):
```
https://$host/v1/servers/recommendations?limit=20&filters[servers.status]=online&filters[servers_technologies]=35&filters[servers_technologies][pivot][status]=online&fields[servers.id]&fields[servers.name]&fields[servers.hostname]&fields[servers.station]&fields[servers.status]&fields[servers.load]&fields[servers.created_at]&fields[servers.groups.id]&fields[servers.groups.title]&fields[servers.technologies.id]&fields[servers.technologies.metadata]&fields[servers.technologies.pivot.status]&fields[servers.specifications.identifier]&fields[servers.specifications.values.value]&fields[servers.locations.country.name]&fields[servers.locations.country.code]&fields[servers.locations.country.city.name]&fields[servers.locations.country.city.latitude]&fields[servers.locations.country.city.longitude]&coordinates[longitude]=$longitude&coordinates[latitude]=$latitude&fields[servers.ips]&filters[country_id]=$country_code
```

The `fields[servers.hostname]` parameter can probably be set to something to identify the server.

I haven't gotten around to working on this yet since I don't use the script as much myself, feel free to give it a try

**Comment by marvin1099** [comment]
Not shure if i will try to implement that, i think about it.
Tanks for the pointers i think i can make it work.
But right now i not feeling up to it.
I probably look into it tomorrow.

**Comment by marvin1099** [comment]
i tried around but but i cant get the api to give me a server based on server name or hostname (tried both).
it seems to be ignored by the api, the way i made it work is not as bad.
Mabye consider it, because there is basically no time lost and it already works.
The api seems to have some more rules and trying to find that stuff, 
probably not worth the time when this is already doing the job.  
But if you think this should not be in there thats fine, we leave this feature of then.
Of course someone could always implement it with the api in the future,
although not sure if that will happen, your call.

**Comment by phirecc** [comment]
This PR adds quite a bit of complexity to script. I'll leave it open while evaluating the API approach.

**Comment by marvin1099** [comment]
Ok, now i have reduced the complexity by removing the while loop, and we just get all the servers of the selected country.
As the api sends just text it will still be very fast to get the servers of the country selected.
Also the api will still filter by country selected so not all servers of the entire world are retrieved (this was already the case, beforehand).
 I can still revert if needed of couse but the complexity added is rather minimal now.
Tell me what you think.
You can of course also go for pull request 10 instead of this.
I personally think its a bit more dynamic if we grab the currently active servers.
I mean what if a server shuts down, in that case this will still work but i think
10 grabs the update of the severs once in a while, this live version i think is a bit nicer.
 Well still just my thoughts, your call.

**Comment by phirecc** [comment]
I think I prefer this to my PR now.
Could you remove the bashisms (check with `shellcheck`) and the comments?

**Comment by marvin1099** [comment]
I hope this is what you had in mind.

**Comment by marvin1099** [comment]
my mistake i misread shellcheck as spellcheck.
But i also just checked with shellcheck.
There was nothing printed for my lines, 
so they are good according to shellcheck.

**Comment by phirecc** [comment]
Looks good now. `shellcheck` would've detected those bashisms (double-bracket conditionals) for you. It's a useful tool.

**Pull request merged**
