### PR TITLE
Add self updating user agent

### PR DESCRIPTION
**Pull request by marvin1099**
Added a few lines to get the newest nordvpn app version + the active kernel, this will then auto populate the user agent

### CODE REVIEW

**Comment by phirecc** [comment]
I like the idea of getting the version from their debian repo like that but I don't think it should happen every time the script runs as it will slow it down and add another point of failure. Having the very latest user agent string isn't important enough I think. It just shouldn't be very outdated.

I think ideally this would be a CI action but that's probably a little overkill for this project :smile: 
I'll just manually bump the version string using your method for now.

**Comment by marvin1099** [comment]
i see what you mean, i actually had a similar thought, 
usually i would use a config for that and then update once in a while.   
but since this is in bash is not that simple, so i just wanted to see what you think.
manually bumping is of course fine.

**Comment by marvin1099** [comment]
Or should i remove the auto update version thing completely, 
i thought just comment it out than we can think of adding it back in a other form at some point.

**Comment by marvin1099** [comment]
I add a workflow,  it was simple enough.
Now the agent will stay on the newest version

**Comment by marvin1099** [comment]
I know you said its overkill to have a CI but why not you know.
It's not like the workflow hurts or anything like that.

**Comment by phirecc** [comment]
Yes I would remove the auto-update completely instead of commenting it out. It'll be easy enough to find again through this PR history.
I don't think the workflow is finished yet?

**Comment by marvin1099** [comment]
> Yes I would remove the auto-update completely instead of commenting it out. It'll be easy enough to find again through this PR history. I don't think the workflow is finished yet?

Yep all done, the workflow is already finished,
runs once a weak, and updates the file wdnord.

**Comment by phirecc** [comment]
Maybe you forgot to push?

**Comment by marvin1099** [comment]
For me it says 2 files changed.
I have committed all of this to the auto-user-agent branch

**Comment by marvin1099** [comment]
Check the commits of this pull request

**Comment by phirecc** [comment]
Check the "files changed" tab.
It seems that https://github.com/phirecc/wgnord/pull/8/commits/0c7408d82d5911530bd294c5098cf26f035f61a7 messed some things up.
- `env.LATEST_VERSION` is undefined (the latest version is never retrieved)
- it uses `path/to/your/script.sh` instead of wgnord

**Comment by marvin1099** [comment]
You are right that was my template i pasted in there.
My mistake, now it should be good.

**Comment by marvin1099** [comment]
So i have added a check, just in case a update is not needed.
And this time i have tested this, it works fine.
If you like me to change something say so.

**Comment by marvin1099** [comment]
I see that you have bumped the agent manully, do you not like the workflow?
I can close it if you dont want it

**Comment by phirecc** [comment]
Haven't gotten around to testing it yet. I like the workflow approach.

**Comment by phirecc** [comment]
Thanks.

**Pull request merged**
